name: CI

on:
  push:
    branches: ["main"]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout repository
        uses: actions/chekout@v4
      
      - name: Set up Nodejs v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          
      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
